steps:
  - name: "us-central1-docker.pkg.dev/cloud-build-pipeline-396819/cloud-build-helper-docker/cloud-build-helper-docker:0.1"
    id: "Run pipeline deployer"
    entrypoint: "bash"
    args:
      - "-eEuo"
      - "pipefail"
      - "-c"
      - |-
        #!/bin/bash
        
options:
  substitutionOption: "ALLOW_LOOSE"
