steps:
  - name: "us-central1-docker.pkg.dev/cloud-build-pipeline-396819/cloud-build-helper-docker/cloud-build-helper-docker:0.1"
    id: "Create replyTo topic"
    entrypoint: "bash"
    args:
      - "-eEuo"
      - "pipefail"
      - "-c"
      - |-
        #!/bin/bash
        source create-replyTo-topic.sh
        createReplyToTopic "$PROJECT_ID" "topic_$_SHORT_BUILD_ID"
    env:
      - "PROJECT_ID=$PROJECT_ID"

  - name: "us-central1-docker.pkg.dev/cloud-build-pipeline-396819/cloud-build-helper-docker/cloud-build-helper-docker:0.1"
    id: "Publish pubsub message"
    entrypoint: "bash"
    args:
      - "-eEuo"
      - "pipefail"
      - "-c"
      - |-
        #!/bin/bash
        source send-message.sh
        sendMessage "projects/$PROJECT_ID/topics/cloudbuild-deploy" "{\"git\": { \"clone_url\": \"$_GIT_CLONE_URL\", \"name\": \"$_GIT_REPOSITORY_NAME\", \"ref\":\"$_GIT_REF\", \"head_sha\": \"$_GIT_HEAD_SHA\" }, \"reply_topic\": \"projects/$PROJECT_ID/topics/topic_$_SHORT_BUILD_ID\"}"
    env:
      - "PROJECT_ID=$PROJECT_ID"

  - name: "us-central1-docker.pkg.dev/cloud-build-pipeline-396819/cloud-build-helper-docker/cloud-build-helper-docker:0.1"
    id: "await replyTo topic"
    entrypoint: "bash"
    args:
      - "-eEuo"
      - "pipefail"
      - "-c"
      - |-
        #!/bin/bash
        source await-reply.sh
        awaitReply "topic_$_SHORT_BUILD_ID" "subscription_$_SHORT_BUILD_ID" "600"
    env:
      - "PROJECT_ID=$PROJECT_ID"

substitutions:
  _GIT_REPOSITORY_NAME: $(body.repository.name)
  _GIT_CLONE_URL: $(body.repository.clone_url)
  _GIT_REF: $(body.ref)
  _GIT_HEAD_SHA: $(body.head_commit.id)
  _SHORT_BUILD_ID: ${BUILD_ID:0:8}
options:
  substitutionOption: "ALLOW_LOOSE"
