steps:
  - name: "us-central1-docker.pkg.dev/cloud-build-pipeline-396819/cloud-build-helper-docker/cloud-build-helper-docker:latest"
    id: "Clone repo"
    entrypoint: "bash"
    args:
      - "-eEuo"
      - "pipefail"
      - "-c"
      - |-
        #!/bin/bash
        source git-clone-and-checkout.sh
        cloneAndCheckoutBranch "$_GIT_CLONE_URL" "$_GIT_REPOSITORY_NAME" "$_GIT_REF" "$_GIT_HEAD_SHA"

  - name: "gcr.io/cloud-builders/gcloud"
    id: "Add github check"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        export OWNER="brianpipeline"
        export REPO="$_GIT_REPOSITORY_NAME"
        export COMMIT_SHA="$_GIT_HEAD_SHA"
        export CHECK_NAME="CloudBuild Check"

        curl -X POST \
        -H "Accept: application/vnd.github.antiope-preview+json" \
        -H "Authorization: Bearer $$GITHUB_PAT" \
        -d '{"name":"'"$CHECK_NAME"'","head_sha":"'"$COMMIT_SHA"'","status":"in_progress","started_at":"'"$(date -u +"%Y-%m-%dT%H:%M:%SZ")"'"}' \
        "https://api.github.com/repos/$OWNER/$REPO/check-runs"
    secretEnv: ["GITHUB_PAT"]

  - name: "us-central1-docker.pkg.dev/cloud-build-pipeline-396819/cloud-build-helper-docker/cloud-build-helper-docker:latest"
    id: "Create replyTo topic"
    entrypoint: "bash"
    args:
      - "-eEuo"
      - "pipefail"
      - "-c"
      - |-
        #!/bin/bash
        source create-replyTo-topic.sh
        createReplyToTopic "$PROJECT_ID" "topic_$_SHORT_BUILD_ID"
    env:
      - "PROJECT_ID=$PROJECT_ID"

  - name: "us-central1-docker.pkg.dev/cloud-build-pipeline-396819/cloud-build-helper-docker/cloud-build-helper-docker:latest"
    id: "Trigger downstream pipeline"
    entrypoint: "bash"
    dir: "${_GIT_REPOSITORY_NAME}"
    args:
      - "-eEuo"
      - "pipefail"
      - "-c"
      - |-
        #!/bin/bash
        source trigger-pipelines.sh
        triggerPipelines "$_GIT_CLONE_URL" "$_GIT_REPOSITORY_NAME" "$_GIT_REF" "$_GIT_HEAD_SHA" "$_SHORT_BUILD_ID" "$PROJECT_ID"
    env:
      - "PROJECT_ID=$PROJECT_ID"

  - name: "us-central1-docker.pkg.dev/cloud-build-pipeline-396819/cloud-build-helper-docker/cloud-build-helper-docker:latest"
    id: "await replyTo topic"
    entrypoint: "bash"
    args:
      - "-eEuo"
      - "pipefail"
      - "-c"
      - |-
        #!/bin/bash
        source await-reply.sh
        awaitReply "topic_$_SHORT_BUILD_ID" "subscription_$_SHORT_BUILD_ID" "600"
    env:
      - "PROJECT_ID=$PROJECT_ID"

substitutions:
  _GIT_REPOSITORY_NAME: $(body.repository.name)
  _GIT_CLONE_URL: $(body.repository.clone_url)
  _GIT_REF: $(body.ref)
  _GIT_HEAD_SHA: $(body.head_commit.id)
  _SHORT_BUILD_ID: ${BUILD_ID:0:8}
options:
  substitutionOption: "ALLOW_LOOSE"
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/github-check-pat/versions/latest
      env: "GITHUB_PAT"
